type Props = {
  content: string;
  repository: string;
};

function ExportButtons({ content, repository }: Props) {
  const downloadMarkdown = () => {
    const markdown = `# RepoMind AI Repository Report

**Repository:** ${repository}

**Generated by:** RepoMind AI

**Generated on:** ${new Date().toLocaleString()}

---

${content}
`;

    const blob = new Blob([markdown], {
      type: "text/markdown;charset=utf-8",
    });

    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");
    link.href = url;
    link.download = `${repository || "repository"}-analysis.md`;

    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex gap-3">
      <button
        onClick={downloadMarkdown}
        className="rounded-lg border border-slate-700 bg-slate-800 px-4 py-2 text-sm font-medium text-slate-200 transition hover:bg-slate-700"
      >
        Download Report
      </button>
    </div>
  );
}

export default ExportButtons;